"""
This type stub file was generated by pyright.
"""

from typing_extensions import Final
from webservice_hidro.enums_hidro import TipoDeDados, TipoDeVariavel

ASSOCIACAO_TIPO_DADO_VARIAVEL: Final[dict[TipoDeDados, TipoDeVariavel]] = ...
