"""
This type stub file was generated by pyright.
"""

from webservice_hidro.enums_hidro import TipoDeDados

def exporta_dados_hidro(): # -> None:
    ...

def exporta_dados_hidro_por_geometria(caminho_geometria: str, tipo_de_dados: TipoDeDados, diretorio_saida: str, data_inicial: str = ..., data_final: str = ...) -> None:
    """Exporta dados das Estações em arquiovs CSV que interseccionam a geometria
        passada como parâmetro em formato shape pu geopackage

    Args:
        caminho_geometria (str): Caminho onde se encontra o qruivos com a geometria
            [Shape (.shp) ou Geopackage (.gpkg)]
        tipo_de_dados (hidro.TipoDeDados): Tipo de Dado: 1=COTAS; 2=CHUVAS; 3=VAZOES
        diretorio_saida (str): Diretório onde se deseja salvar os arquivos CSV
        data_inicial (str, optional): Data inicial das séries temporais. Defaults to '01/01/1900'.
        data_final (str, optional): Data Final das séries temporais. Defaults to ''.
    """
    ...

