"""
This type stub file was generated by pyright.
"""

import pandas as pd
from ..enums_hidro import TipoDeDados, TipoDeVariavel
from ..models import PivotChuva, PivotCota, PivotVazao

PivotSerieType = type[PivotCota] | type[PivotChuva] | type[PivotVazao]
PivotSerieInstance = PivotCota | PivotChuva | PivotVazao
CLASSES_VARIAVEIS: dict[TipoDeVariavel, PivotSerieType] = ...
def retorna_serie_historica(codEstacao: str | int, tipoDados: TipoDeDados, dataInicio: str = ..., dataFim: str = ..., nivelConsistencia: int = ...) -> pd.DataFrame:
    """Retorna DataFrame da série histórica da estação selecionada
       no formato da tabela do HidroWeb.

    Args:
        codEstacao (str): Código Plu ou Flu.
        tipoDados (int): 1-Cotas, 2-Chuvas ou 3-Vazões.
        dataInicio (str): Data inicial. Formato: dd/mm/aaaa
        dataFim (str, optional): Data inicial. Formato: dd/mm/aaaa. Defaults to "".
          Caso não preenchido, trará até o último dado mais recente.
        nivelConsistencia (int, optional): 1-Bruto ou 2-Consistido. Defaults to 2.

    Returns:
         DataFrame: Dicionário com os dados da série histórica.
    """
    ...

def reorganiza_serie_em_coluna(dados_api: pd.DataFrame, variavel: TipoDeVariavel) -> pd.DataFrame:
    """Reorganiza o DataFrame da série histórica com os dados
       em uma única coluna sequencial de data.

    Args:
        serie_historica (pd.DataFrame): DataFrame original extraída do webservice

    Returns:
        pd.DataFrame: DataFrame com dados em sequência de data.
    """
    ...

